<div class= "Container">
            <div class="Title">
              <a>Document Files</a>
            </div>
            <!-- Info -->
                <div class="Info">
                  <a><button type="button" class="BTN" data-toggle="collapse" data-target="#DATA">Satisfaction Survey</button></a>
                </div>
                <div id="DATA" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div>
                <!-- Info -->
                <div class="Info">
                  <a><button type="button" class="BTN" data-toggle="collapse" data-target="#DATA1" >Leadership Survey</button></a>
                </div>
                <div id="DATA1" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div>
                <!-- Info -->
                <div class="Info">
                  <a><button type="button" class="BTN" data-toggle="collapse" data-target="#DATA2">Assessment Committee</button></a>
                </div>
                <div id="DATA2" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div>
                <!-- Info -->
                <div class="Info">
                  <a><button type="button" class="BTN" data-toggle="collapse" data-target="#DATA3">Assessment Instruments</button></a>
                </div>
                <div id="DATA3" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div>
                <!-- Info -->
                <div class="Info">
                  <a><button type="button" class="BTN" data-toggle="collapse" data-target="#DATA4">Institutional Reports</button></a>
                </div>
                <div id="DATA4" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div>
                <!-- Info -->
                <div class="Info">
                  <a><button type="button" class="BTN" data-toggle="collapse" data-target="#DATA5">Assessment Reports</button></a>
                </div>
                <div id="DATA5" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div>
                <!-- Info -->
                <div class="Info">
                  <a><button type="button" class="BTN" data-toggle="collapse" data-target="#DATA6">Miscellaneous</button></a>
                </div>
                <div id="DATA6" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div>
                <!-- Info -->
</div>