<div class= "Container">
            <div class="Title">
              <a>Document Files</a>
            </div>
            <!-- Info -->
                <div class="Info">
                  <a><button type="button" class="BTN" >Satisfaction Survey</button></a>
                </div>
                <!-- Info -->
                <div class="Info">
                  <a><button type="button" class="BTN" >Leadership Survey</button></a>
                </div>
                <!-- Info -->
                <div class="Info">
                  <a><button type="button" class="BTN" >Assessment Committee</button></a>
                </div>
                <!-- Info -->
                <div class="Info">
                  <a><button type="button" class="BTN" >Assessment Instruments</button></a>
                </div>
                <!-- Info -->
                <div class="Info">
                  <a><button type="button" class="BTN" >Institutional Reports</button></a>
                </div>
                <!-- Info -->
                <div class="Info">
                  <a><button type="button" class="BTN" >Assessment Reports</button></a>
                </div>
                <!-- Info -->
                <div class="Info">
                  <a><button type="button" class="BTN" >Miscellaneous</button></a>
                </div>
                <!-- Info -->
</div>