<div class="Container">
            <div class="Title">
              <a>UPR Ponce</a>
            </div>
            <!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" ID="BTN1" data-toggle="collapse" data-target="#DATA">Mission and vision</button></a>
            </div>
                <div id="DATA" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div><!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" ID="BTN1" data-toggle="collapse" data-target="#DATA2">Program Goals</button></a>
            </div>
                <div id="DATA2" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div><!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" ID="BTN1" data-toggle="collapse" data-target="#DATA3">Students Profile</button></a>
            </div>
                <div id="DATA3" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div><!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" ID="BTN1" data-toggle="collapse" data-target="#DATA4">Strategic Plan</button></a>
            </div>
                <div id="DATA4" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div><!-- Info -->
            <div class="Info">
              <a href="http://www.uprp.edu/"><button type="button" ID="BTN1" class="BTN" >Website</button></a>
            </div>
               
        </div><!-- Col -->