<div class= "Container">
            <div class="Title">
                <a>UPR Ponce Business Program</a>
            </div>
            <!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" >Program Information</button></a>
            </div>
            <!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" >Mission and Vision</button></a>
            </div>
            <!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" >Program Goals</button></a>
            </div>
            <!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" >Student Profile</button></a>
            </div>
            <!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" >Strategic Plan</button></a>
            </div>
            <!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" >Weblinks</button></a>
            </div>
            <!-- Info -->
        </div>