<div class="Container">
            <div class="Title">
              <a>UPR Ponce</a>
            </div><!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" >Mission and vision</button></a>
            </div><!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" >Program Goals</button></a>
            </div><!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" >Students Profile</button></a>
            </div><!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" >Strategic Plan</button></a>
            </div><!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" >Website</button></a>
            </div><!-- Info -->
        </div><!-- Col -->