<div class= "Container">
            <div class="Title">
                <a>UPR Ponce Business Program</a>
            </div>
            <!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" data-toggle="collapse" data-target="#DATA">Program Information</button></a>
            </div>
                <div id="DATA" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div><!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" data-toggle="collapse" data-target="#DATA2">Mission and Vision</button></a>
            </div>
                <div id="DATA2" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div><!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" data-toggle="collapse" data-target="#DATA3">Program Goals</button></a>
            </div>
                <div id="DATA3" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div><!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" data-toggle="collapse" data-target="#DATA4">Student Profile</button></a>
            </div>
                <div id="DATA4" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div><!-- Info -->
            <div class="Info">
              <a><button type="button" class="BTN" data-toggle="collapse" data-target="#DATA5">Strategic Plan</button></a>
            </div>
                <div id="DATA5" class="collapse">
                <embed src="files/UAMystic3.pdf" type="application/pdf" width="100%" height="500px" />
                </div><!-- Info -->
            <div class="Info">
              <a href="http://www.uprp.edu/index.php?option=com_content&view=article&id=231&Itemid=434&LinkId=67"><button type="button" class="BTN" >Weblinks</button></a>
            </div>
            <!-- Info -->
        </div>